/** Query keys. `health` and `fieldLabels` are additions. */
export const queryKeys = {
  health: ['health'] as const,
  journals: ['journals'] as const,
  settings: ['settings'] as const,
  tags: ['tags'] as const,
  notes: (filters: unknown) => ['notes', filters] as const,
  notesAll: ['notes'] as const,
  notesCount: (filters: unknown) => ['notes', 'count', filters] as const,
  note: (id: string) => ['note', id] as const,
  people: (params: unknown) => ['people', params] as const,
  peopleAll: ['people'] as const,
  person: (id: string) => ['person', id] as const,
  personNotes: (id: string) => ['person', id, 'notes'] as const,
  plantings: (params: unknown) => ['plantings', params] as const,
  plantingsAll: ['plantings'] as const,
  planting: (id: string) => ['planting', id] as const,
  plantingNotes: (id: string) => ['planting', id, 'notes'] as const,
  maps: ['maps'] as const,
  map: (id: string) => ['map', id] as const,
  places: ['maps', 'places'] as const,
  pinsFor: (type: string, id: string) => ['maps', 'pins', type, id] as const,
  fieldLabels: (kind: string, q: string) => ['fieldLabels', kind, q] as const,
  search: (q: string, kinds: string) => ['search', q, kinds] as const,
  pick: (kind: string, q: string) => ['pick', kind, q] as const,
  trash: ['trash'] as const,
  dataInfo: ['data', 'info'] as const,
  backups: ['data', 'backups'] as const,
  phone: ['phone'] as const,
};

/** Everything that depends on records: used after imports, restores and other broad changes. */
export const ALL_DATA_KEYS: readonly (readonly unknown[])[] = [
  ['notes'],
  ['note'],
  ['people'],
  ['person'],
  ['plantings'],
  ['planting'],
  ['maps'],
  ['map'],
  ['tags'],
  ['search'],
  ['pick'],
  ['trash'],
  ['data'],
  ['settings'],
  ['fieldLabels'],
];
